# Generated by Django 4.2.3 on 2023-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_options_alter_goods_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'характеристику', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goodscharacteristic',
            options={'verbose_name': 'характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='providers',
            options={'verbose_name': 'поставщика', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='provider_name',
            field=models.CharField(max_length=255, verbose_name='Имя поставщика'),
        ),
    ]
